Update android.yml

diff --git a/.github/workflows/android.yml b/.github/workflows/android.yml
--- a/.github/workflows/android.yml
+++ b/.github/workflows/android.yml
@@ -103,8 +103,11 @@ jobs:
             clang++ --version
 
             echo "=== 生成Makefile ==="
-            qmake.bat Knot.pro -spec android-clang CONFIG+=release ANDROID_ABIS=arm64-v8a
-            #if errorlevel 1 exit 1
+            call qmake.bat Knot.pro -spec android-clang CONFIG+=release ANDROID_ABIS=arm64-v8a
+            if errorlevel 1 (
+                  echo "::error::qmake失败！"
+                  exit 1
+                )
 
             echo "=== 检查Makefile中的源文件 ==="
             type Makefile | findstr /C:"SOURCES ="  # 确认是否包含你的.cpp文件
